### ISSUE TITLE
Issues with build on Linux

### ISSUE THREAD

**Issue by ramiropolla** [pawelzwronek/LiveMosher#1]
Hi,

I  had a few issues with building on Linux:
- I had to `pip install scikit-build`. Perhaps it should be added to `requirements-*.txt`
- It would help if the `.sh` files had the executable bit set: `chmod +x *.sh`
- The executables should also have the executable bit set: `chmod +x bin/ffglitch/linux/*` (the same is probably needed for Windows and/or macOS)
- I had to `sudo apt-get install python3-tk`. Perhaps that should be listed as a requirement in `README.md`.
- Building seems to modify files in the source directory (`src/LiveMosherApp.py` and `src/script.py`), which is generally not a good idea.

I'll test more over the next few days.

Ramiro

**Comment by pawelzwronek** [comment]
Hello Ramiro. Thanks for testing my app and sharing those issues. Just fixed them with latest commits.
As pyinstaller suggested I had to install `binutils` and it worked. I think it's substitution for `scikit-build` in your case.
I was testing on a clean installation of Ubuntu 20 on VirtualBox. Snapshots are great for restoring clean state of the OS :)

**Comment by ramiropolla** [comment]
Hi,

`binutils` is a separate project unrelated to `scikit-build`. On a new machine, I had to run the commands specified here <https://pypi.org/project/tkextrafont/>:
```
$ sudo apt install python3-dev tcl-dev tk-dev \
    fontconfig libfontconfig1 libfontconfig1-dev \
    cmake cmake-data extra-cmake-modules build-essential
$ source venv-linux/bin/activate
$ python -m pip install scikit-build
```

Then exit the virtual env and `./venv-prepare.sh` worked. It's not such a big deal since I suppose most people will just get the binaries you release, but I just though I'd let you know.

Ramiro

**Comment by pawelzwronek** [comment]
That's strange. On my clean(updated) distro:
```bash
p@p-VirtualBox:~/LiveMosher$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

p@p-VirtualBox:~/LiveMosher$ uname -a
Linux p-VirtualBox 5.15.0-125-generic #135~20.04.1-Ubuntu SMP Mon Oct 7 13:56:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

I need to run only those commands to get a working app in a `dist` folder:
```bash
sudo apt install git
git clone https://github.com/pawelzwronek/LiveMosher.git
sudo apt install binutils python3-venv python3-tk
cd LiveMosher/
./venv-prepare.sh
./run_pyinstaller-linux.sh
```

I wonder what errors and when do you get?

**Comment by pawelzwronek** [comment]
Full log:
```bash
p@p-VirtualBox:~$ git

Command 'git' not found, but can be installed with:

sudo apt install git

p@p-VirtualBox:~$ sudo apt install git
[sudo] password for p: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  git git-man liberror-perl
0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.
Need to get 5 525 kB of archives.
After this operation, 38,8 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://security.ubuntu.com/ubuntu focal-security/main amd64 git-man all 1:2.25.1-1ubuntu3.13 [887 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security/main amd64 git amd64 1:2.25.1-1ubuntu3.13 [4 612 kB]
Get:3 http://pl.archive.ubuntu.com/ubuntu focal/main amd64 liberror-perl all 0.17029-1 [26,5 kB]
Fetched 5 525 kB in 1s (9 009 kB/s)                                        
Selecting previously unselected package liberror-perl.
(Reading database ... 157620 files and directories currently installed.)
Preparing to unpack .../liberror-perl_0.17029-1_all.deb ...
Unpacking liberror-perl (0.17029-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.25.1-1ubuntu3.13_all.deb ...
Unpacking git-man (1:2.25.1-1ubuntu3.13) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.25.1-1ubuntu3.13_amd64.deb ...
Unpacking git (1:2.25.1-1ubuntu3.13) ...
Setting up liberror-perl (0.17029-1) ...
Setting up git-man (1:2.25.1-1ubuntu3.13) ...
Setting up git (1:2.25.1-1ubuntu3.13) ...
Processing triggers for man-db (2.9.1-1) ...
p@p-VirtualBox:~$ ls
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
p@p-VirtualBox:~$ git clone https://github.com/pawelzwronek/LiveMosher.git
Cloning into 'LiveMosher'...
remote: Enumerating objects: 497, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 497 (delta 3), reused 7 (delta 1), pack-reused 477 (from 1)
Receiving objects: 100% (497/497), 46.43 MiB | 5.97 MiB/s, done.
Resolving deltas: 100% (106/106), done.
p@p-VirtualBox:~$ sudo apt install binutils python3-venv python3-tk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  binutils-common binutils-x86-64-linux-gnu blt libbinutils libctf-nobfd0 libctf0 libtcl8.6 libtk8.6 python-pip-whl python3-distutils python3-lib2to3 python3.8-venv tk8.6-blt2.5
Suggested packages:
  binutils-doc blt-demo tcl8.6 tk8.6 tix python3-tk-dbg
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu blt libbinutils libctf-nobfd0 libctf0 libtcl8.6 libtk8.6 python-pip-whl python3-distutils python3-lib2to3 python3-tk python3-venv
  python3.8-venv tk8.6-blt2.5
0 upgraded, 16 newly installed, 0 to remove and 1 not upgraded.
Need to get 6 724 kB of archives.
After this operation, 27,7 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://pl.archive.ubuntu.com/ubuntu focal/main amd64 libtcl8.6 amd64 8.6.10+dfsg-1 [902 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security/main amd64 binutils-common amd64 2.34-6ubuntu1.9 [208 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security/main amd64 libbinutils amd64 2.34-6ubuntu1.9 [475 kB]
Get:4 http://pl.archive.ubuntu.com/ubuntu focal/main amd64 libtk8.6 amd64 8.6.10-1 [714 kB]
Get:5 http://pl.archive.ubuntu.com/ubuntu focal/main amd64 tk8.6-blt2.5 amd64 2.5.3+dfsg-4 [572 kB]
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 libctf-nobfd0 amd64 2.34-6ubuntu1.9 [48,2 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 libctf0 amd64 2.34-6ubuntu1.9 [46,6 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main amd64 binutils-x86-64-linux-gnu amd64 2.34-6ubuntu1.9 [1 614 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 binutils amd64 2.34-6ubuntu1.9 [3 380 B]
Get:10 http://security.ubuntu.com/ubuntu focal-security/universe amd64 python-pip-whl all 20.0.2-5ubuntu1.11 [1 808 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/main amd64 python3-lib2to3 all 3.8.10-0ubuntu1~20.04 [76,3 kB]
Get:12 http://security.ubuntu.com/ubuntu focal-security/main amd64 python3-distutils all 3.8.10-0ubuntu1~20.04 [141 kB]
Get:13 http://security.ubuntu.com/ubuntu focal-security/main amd64 python3-tk amd64 3.8.10-0ubuntu1~20.04 [104 kB]
Get:14 http://security.ubuntu.com/ubuntu focal-security/universe amd64 python3.8-venv amd64 3.8.10-0ubuntu1~20.04.13 [5 452 B]
Get:15 http://pl.archive.ubuntu.com/ubuntu focal/main amd64 blt amd64 2.5.3+dfsg-4 [4 944 B]
Get:16 http://pl.archive.ubuntu.com/ubuntu focal/universe amd64 python3-venv amd64 3.8.2-0ubuntu2 [1 228 B]
Fetched 6 724 kB in 0s (14,8 MB/s)            
Selecting previously unselected package binutils-common:amd64.
(Reading database ... 158555 files and directories currently installed.)
Preparing to unpack .../00-binutils-common_2.34-6ubuntu1.9_amd64.deb ...
Unpacking binutils-common:amd64 (2.34-6ubuntu1.9) ...
Selecting previously unselected package libbinutils:amd64.
Preparing to unpack .../01-libbinutils_2.34-6ubuntu1.9_amd64.deb ...
Unpacking libbinutils:amd64 (2.34-6ubuntu1.9) ...
Selecting previously unselected package libctf-nobfd0:amd64.
Preparing to unpack .../02-libctf-nobfd0_2.34-6ubuntu1.9_amd64.deb ...
Unpacking libctf-nobfd0:amd64 (2.34-6ubuntu1.9) ...
Selecting previously unselected package libctf0:amd64.
Preparing to unpack .../03-libctf0_2.34-6ubuntu1.9_amd64.deb ...
Unpacking libctf0:amd64 (2.34-6ubuntu1.9) ...
Selecting previously unselected package binutils-x86-64-linux-gnu.
Preparing to unpack .../04-binutils-x86-64-linux-gnu_2.34-6ubuntu1.9_amd64.deb ...
Unpacking binutils-x86-64-linux-gnu (2.34-6ubuntu1.9) ...
Selecting previously unselected package binutils.
Preparing to unpack .../05-binutils_2.34-6ubuntu1.9_amd64.deb ...
Unpacking binutils (2.34-6ubuntu1.9) ...
Selecting previously unselected package libtcl8.6:amd64.
Preparing to unpack .../06-libtcl8.6_8.6.10+dfsg-1_amd64.deb ...
Unpacking libtcl8.6:amd64 (8.6.10+dfsg-1) ...
Selecting previously unselected package libtk8.6:amd64.
Preparing to unpack .../07-libtk8.6_8.6.10-1_amd64.deb ...
Unpacking libtk8.6:amd64 (8.6.10-1) ...
Selecting previously unselected package tk8.6-blt2.5.
Preparing to unpack .../08-tk8.6-blt2.5_2.5.3+dfsg-4_amd64.deb ...
Unpacking tk8.6-blt2.5 (2.5.3+dfsg-4) ...
Selecting previously unselected package blt.
Preparing to unpack .../09-blt_2.5.3+dfsg-4_amd64.deb ...
Unpacking blt (2.5.3+dfsg-4) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../10-python-pip-whl_20.0.2-5ubuntu1.11_all.deb ...
Unpacking python-pip-whl (20.0.2-5ubuntu1.11) ...
Selecting previously unselected package python3-lib2to3.
Preparing to unpack .../11-python3-lib2to3_3.8.10-0ubuntu1~20.04_all.deb ...
Unpacking python3-lib2to3 (3.8.10-0ubuntu1~20.04) ...
Selecting previously unselected package python3-distutils.
Preparing to unpack .../12-python3-distutils_3.8.10-0ubuntu1~20.04_all.deb ...
Unpacking python3-distutils (3.8.10-0ubuntu1~20.04) ...
Selecting previously unselected package python3-tk:amd64.
Preparing to unpack .../13-python3-tk_3.8.10-0ubuntu1~20.04_amd64.deb ...
Unpacking python3-tk:amd64 (3.8.10-0ubuntu1~20.04) ...
Selecting previously unselected package python3.8-venv.
Preparing to unpack .../14-python3.8-venv_3.8.10-0ubuntu1~20.04.13_amd64.deb ...
Unpacking python3.8-venv (3.8.10-0ubuntu1~20.04.13) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../15-python3-venv_3.8.2-0ubuntu2_amd64.deb ...
Unpacking python3-venv (3.8.2-0ubuntu2) ...
Setting up binutils-common:amd64 (2.34-6ubuntu1.9) ...
Setting up libctf-nobfd0:amd64 (2.34-6ubuntu1.9) ...
Setting up libtcl8.6:amd64 (8.6.10+dfsg-1) ...
Setting up python-pip-whl (20.0.2-5ubuntu1.11) ...
Setting up libbinutils:amd64 (2.34-6ubuntu1.9) ...
Setting up python3-lib2to3 (3.8.10-0ubuntu1~20.04) ...
Setting up libctf0:amd64 (2.34-6ubuntu1.9) ...
Setting up python3-distutils (3.8.10-0ubuntu1~20.04) ...
Setting up libtk8.6:amd64 (8.6.10-1) ...
Setting up python3.8-venv (3.8.10-0ubuntu1~20.04.13) ...
Setting up binutils-x86-64-linux-gnu (2.34-6ubuntu1.9) ...
Setting up tk8.6-blt2.5 (2.5.3+dfsg-4) ...
Setting up blt (2.5.3+dfsg-4) ...
Setting up python3-tk:amd64 (3.8.10-0ubuntu1~20.04) ...
Setting up binutils (2.34-6ubuntu1.9) ...
Setting up python3-venv (3.8.2-0ubuntu2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.16) ...
p@p-VirtualBox:~$ cd LiveMosher/
p@p-VirtualBox:~/LiveMosher$ ./venv-prepare.sh 
Setting up virtual environment for linux
Collecting pyinstaller==6.11.0
  Downloading pyinstaller-6.11.0-py3-none-manylinux2014_x86_64.whl (707 kB)
     |████████████████████████████████| 707 kB 3.0 MB/s 
Collecting vermin==1.6.0
  Downloading vermin-1.6.0-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 11.1 MB/s 
Collecting pyzmq==26.1.1
  Downloading pyzmq-26.1.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (862 kB)
     |████████████████████████████████| 862 kB 26.7 MB/s 
Collecting Pygments==2.12.0
  Downloading Pygments-2.12.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 122.7 MB/s 
Collecting pygments-ansi-color==0.3.0
  Downloading pygments_ansi_color-0.3.0-py3-none-any.whl (10 kB)
Collecting tkextrafont
  Downloading tkextrafont-0.6.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 58.5 MB/s 
Collecting packaging>=22.0
  Downloading packaging-24.2-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 7.7 MB/s 
Collecting importlib-metadata>=4.6; python_version < "3.10"
  Downloading importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Collecting pyinstaller-hooks-contrib>=2024.8
  Downloading pyinstaller_hooks_contrib-2024.10-py3-none-any.whl (338 kB)
     |████████████████████████████████| 338 kB 68.8 MB/s 
Requirement already satisfied: setuptools>=42.0.0 in ./venv-linux/lib/python3.8/site-packages (from pyinstaller==6.11.0->-r requirements-all.txt (line 2)) (44.0.0)
Collecting altgraph
  Downloading altgraph-0.17.4-py2.py3-none-any.whl (21 kB)
Collecting scikit-build
  Downloading scikit_build-0.18.1-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 8.1 MB/s 
Collecting zipp>=3.20
  Downloading zipp-3.20.2-py3-none-any.whl (9.2 kB)
Collecting wheel>=0.32.0
  Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 2.0 MB/s 
Collecting distro
  Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Collecting tomli; python_version < "3.11"
  Downloading tomli-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: packaging, zipp, importlib-metadata, pyinstaller-hooks-contrib, altgraph, pyinstaller, vermin, pyzmq, Pygments, pygments-ansi-color, wheel, distro, tomli, scikit-build, tkextrafont
Successfully installed Pygments-2.12.0 altgraph-0.17.4 distro-1.9.0 importlib-metadata-8.5.0 packaging-24.2 pygments-ansi-color-0.3.0 pyinstaller-6.11.0 pyinstaller-hooks-contrib-2024.10 pyzmq-26.1.1 scikit-build-0.18.1 tkextrafont-0.6.3 tomli-2.2.1 vermin-1.6.0 wheel-0.45.1 zipp-3.20.2
p@p-VirtualBox:~/LiveMosher$ ./run_pyinstaller-linux.sh
Building for linux
66 INFO: PyInstaller: 6.11.0, contrib hooks: 2024.10
66 INFO: Python: 3.8.10
73 INFO: Platform: Linux-5.15.0-125-generic-x86_64-with-glibc2.29
73 INFO: Python environment: /home/p/LiveMosher/venv-linux
73 INFO: wrote /home/p/LiveMosher/Live Mosher.spec
76 INFO: Module search paths (PYTHONPATH):
['/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages',
 '/home/p/LiveMosher/src']
204 INFO: Appending 'datas' from .spec
205 INFO: checking Analysis
205 INFO: Building Analysis because Analysis-00.toc is non existent
205 INFO: Running Analysis Analysis-00.toc
205 INFO: Target bytecode optimization level: 0
205 INFO: Initializing module dependency graph...
206 INFO: Initializing module graph hook caches...
212 INFO: Analyzing base_library.zip ...
553 INFO: Processing standard module hook 'hook-heapq.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks'
648 INFO: Processing standard module hook 'hook-encodings.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks'
1255 INFO: Processing standard module hook 'hook-pickle.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks'
1778 INFO: Caching module dependency graph...
1836 INFO: Looking for Python shared library...
1850 INFO: Using Python shared library: /lib/x86_64-linux-gnu/libpython3.8.so.1.0
1850 INFO: Analyzing /home/p/LiveMosher/src/LiveMosherApp.py
1974 INFO: Processing standard module hook 'hook-_tkinter.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks'
1992 INFO: Processing standard module hook 'hook-zmq.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/stdhooks'
2171 INFO: Processing standard module hook 'hook-platform.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks'
2193 INFO: Processing pre-safe-import-module hook 'hook-typing_extensions.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module'
2193 INFO: SetuptoolsInfo: initializing cached setuptools info...
2558 INFO: Processing standard module hook 'hook-pygments.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks'
3111 INFO: Processing module hooks (post-graph stage)...
3122 INFO: Processing standard module hook 'hook-_tkinter.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks'
3122 INFO: TclTkInfo: initializing cached Tcl/Tk info...
3164 WARNING: TclTkInfo: Tcl module directory '/usr/share/tcltk/tcl8' does not exist!
4296 INFO: Performing binary vs. data reclassification (340 entries)
4311 INFO: Looking for ctypes DLLs
4314 INFO: Analyzing run-time hooks ...
4318 INFO: Including run-time hook 'pyi_rth_inspect.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks/rthooks'
4319 INFO: Including run-time hook 'pyi_rth__tkinter.py' from '/home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/hooks/rthooks'
4332 INFO: Looking for dynamic libraries
4717 INFO: Warnings written to /home/p/LiveMosher/build/Live Mosher/warn-Live Mosher.txt
4737 INFO: Graph cross-reference written to /home/p/LiveMosher/build/Live Mosher/xref-Live Mosher.html
4754 INFO: checking PYZ
4754 INFO: Building PYZ because PYZ-00.toc is non existent
4754 INFO: Building PYZ (ZlibArchive) /home/p/LiveMosher/build/Live Mosher/PYZ-00.pyz
5015 INFO: Building PYZ (ZlibArchive) /home/p/LiveMosher/build/Live Mosher/PYZ-00.pyz completed successfully.
5021 WARNING: Ignoring icon; supported only on Windows and macOS!
5021 WARNING: Ignoring hide_console; supported only on Windows!
5029 INFO: checking PKG
5029 INFO: Building PKG because PKG-00.toc is non existent
5029 INFO: Building PKG (CArchive) Live Mosher.pkg
5051 INFO: Building PKG (CArchive) Live Mosher.pkg completed successfully.
5052 INFO: Bootloader /home/p/LiveMosher/venv-linux/lib/python3.8/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
5052 INFO: checking EXE
5052 INFO: Building EXE because EXE-00.toc is non existent
5052 INFO: Building EXE from EXE-00.toc
5052 INFO: Copying bootloader EXE to /home/p/LiveMosher/build/Live Mosher/Live Mosher
5052 INFO: Appending PKG archive to custom ELF section in EXE
5061 INFO: Building EXE from EXE-00.toc completed successfully.
5064 INFO: checking COLLECT
5064 INFO: Building COLLECT because COLLECT-00.toc is non existent
5064 INFO: Building COLLECT COLLECT-00.toc
5139 INFO: Building COLLECT COLLECT-00.toc completed successfully.
p@p-VirtualBox:~/LiveMosher$ uname -r
5.15.0-125-generic
p@p-VirtualBox:~/LiveMosher$ uname -ra
Linux p-VirtualBox 5.15.0-125-generic #135~20.04.1-Ubuntu SMP Mon Oct 7 13:56:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
p@p-VirtualBox:~/LiveMosher$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
p@p-VirtualBox:~/LiveMosher$ uname -a
Linux p-VirtualBox 5.15.0-125-generic #135~20.04.1-Ubuntu SMP Mon Oct 7 13:56:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
p@p-VirtualBox:~/LiveMosher$ 
```

**Comment by genmeblog** [comment]
I've hit it as well. Bulding locally from github source on Ubuntu 24.04.4 LTS (under WSL2).

```
$ ./venv-prepare.sh
Setting up virtual environment for linux
Collecting pyinstaller==6.11.0 (from -r requirements-all.txt (line 2))
  Downloading pyinstaller-6.11.0-py3-none-manylinux2014_x86_64.whl.metadata (8.4 kB)
Collecting vermin==1.6.0 (from -r requirements-all.txt (line 3))
  Downloading vermin-1.6.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting pyzmq==26.1.1 (from -r requirements-all.txt (line 6))
  Downloading pyzmq-26.1.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.2 kB)
Collecting Pygments==2.12.0 (from -r requirements-all.txt (line 7))
  Downloading Pygments-2.12.0-py3-none-any.whl.metadata (1.5 kB)
Collecting pygments-ansi-color==0.3.0 (from -r requirements-all.txt (line 8))
  Downloading pygments_ansi_color-0.3.0-py3-none-any.whl.metadata (506 bytes)
Collecting tkextrafont (from -r requirements-linux.txt (line 2))
  Downloading tkextrafont-0.6.1.tar.gz (656 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 656.8/656.8 kB 5.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      scikit-build is required to build this project
      install with `python -m pip install scikit-build`
      Traceback (most recent call last):
        File "/home/tsl/src/LiveMosher/venv-linux/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/tsl/src/LiveMosher/venv-linux/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/tsl/src/LiveMosher/venv-linux/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-c5b2zos3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-c5b2zos3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-c5b2zos3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-c5b2zos3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
      ModuleNotFoundError: No module named 'skbuild'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I had to go to the venv-linux and manually run: `./python -m pip install scikit-build`

Then `./venv-prepare.sh` and the rest of the process works.

**Comment by pawelzwronek** [comment]
All should be fixed in the latest 2 commits. Thanks @ramiropolla and @genmeblog for the suggestions and solutions!
